### ISSUE TITLE
Configure docker in project

### ISSUE THREAD

**Issue by danjesus** [danjesus/whishlist#3]

**Comment by Tchinmai7** [comment]
You want a Dockerfile to be written?

**Comment by goggenb** [comment]
As there isn't any information to work from I just started creating a Dockerfile and docker-compose file to run the app within nodejs and postgres images. But I can't even get past the npm install step. Tried in docker, on Fedora and in Windows with newest node and npm versions. 

```
npm ERR! Linux 4.7.3-200.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libpq@1.8.5 install script 'node-gyp rebuild'.
```

**Comment by alexmuller** [comment]
[node-gyp has some dependencies](https://www.npmjs.com/package/node-gyp#installation) that might not be in your container.

**Comment by danjesus** [comment]
Thanks @goggenb and @alexmuller
